### ISSUE TITLE
Dangerous default settings

### ISSUE THREAD

**Issue by igormukhingmailcom** [kosssi/ansible-playbook-laptop#1]
Playing with ansible-playbook-laptop role is dangerous because can rewrite git configuration:
https://github.com/kosssi/ansible-playbook-laptop/blob/master/provisioning/vars/gitconfig.yml

I've posted commit with your name to my repo on github.

**Comment by kosssi** [comment]
Ok thanks for create issue. I have the same problem for my own laptop and work laptop.

I have an idea for change this. I update when I have more time this week ;)

**Comment by igormukhingmailcom** [comment]
Awesome :+1:
